name: Deploy Project

on: [push, workflow_dispatch]

jobs:
  testing:
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - name: Install dependencies
        run: npm ci
      - name: Run test
        run: npm test
  deployment:
    needs: testing
    runs-on: ubuntu-latest
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Get node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
      - name: Install dependencies
        run: npm ci
      - name: Build application
        run: npm run build
      - name: Deploy to server
        run: echo "Deploying"
