name: First workflow

on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Run build
        run: npm ci; npm run build
      - name: Done greeting
        run: echo "Job done"
