name: First workflow

on: workflow_dispatch
jobs:
  first_job:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout node
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0

      - name: Install packages and sRun build
        run: npm ci; npm run build

      - name: Done greeting
        run: echo "Job done"
