name: PR Checks

on:
  pull_request:
    branches:
      - master

jobs:
  checks:
    name: Run PR Checks
    runs-on: ubuntu-latest
    steps:
      - name: Check if PR target branch is ok
        run: |
          branch_name=${GITHUB_HEAD_REF}
          echo "pr branch name: $branch_name"
          
          target_branch=${GITHUB_BASE_REF}
          echo "target branch: $target_branch"
          dev_regex="^(bug|feature|code-cleanup|hotfix)/sprinthub-[0-9]+.*$"
          qa_regex="^kickback/sprinthub-[0-9]+.*$"
          
          if [[ "$branch_name" =~ $dev_regex ]]; then
            echo "Branch name matches the first regex pattern."
            if [[ "$target_branch" != "dev" ]]; then
              echo "but doesn't match target branch"
              exit 1
            fi
          elif [[ "$branch_name" =~ $qa_regex ]]; then
            echo "Branch name matches the second regex pattern."
            if [[ "$target_branch" != "qa" ]]; then
              echo "but doesn't match target branch"
              exit 1
            fi
          else
            echo "Branch name does not match any regex. Exiting..."
            exit 1
          fi
        shell: bash
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.0
          check-latest: true

      - name: Install dependencies
        run: npm install
      
      - name: Build application
        run: npm run build --if=present

